const $ = (id) => document.getElementById(id);
const setStatus = (id, message, ok = false) => { const el=$(id); el.textContent=message; el.classList.remove('muted'); el.style.color=ok?'#5be5cf':'#c9d1e2'; };
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
let currentJob=null, selectedLocalFile=null, transcriptText='', translatedText='', transcriptId=null, lastVoiceUrl=null;

async function generateVoiceAudio(text){
 const response=await fetch('/api/voice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:$('voiceSelect').value})});
 if(!response.ok){let m='Voice generation failed.';try{const d=await response.json();m=d.error||m;}catch{}throw new Error(m);}
 const blob=await response.blob(); if(lastVoiceUrl) URL.revokeObjectURL(lastVoiceUrl); lastVoiceUrl=URL.createObjectURL(blob); return lastVoiceUrl;
}
async function translateText(text){
 const response=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,targetLanguage:$('targetLanguage').value})});
 const data=await response.json(); if(!response.ok) throw new Error(data.error||'Translation failed.'); return data.translatedText;
}
async function pollTranscript(id){
 for(let i=0;i<120;i++){const r=await fetch(`/api/transcript-status?id=${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to read transcription status.');const t=d.transcript;if(t.status==='completed'){transcriptText=t.text||'';return t;}if(t.status==='error')throw new Error(t.error||'Transcription failed.');setStatus('subtitleStatus',`Transcribing… ${t.status||'processing'}`);await sleep(3000);}throw new Error('Transcription is taking longer than expected.');
}
$('pasteBtn').addEventListener('click',async()=>{try{$('videoLink').value=await navigator.clipboard.readText();}catch{setStatus('sourceStatus','Clipboard permission unavailable. Paste manually.');}});
$('importBtn').addEventListener('click',async()=>{const videoUrl=$('videoLink').value.trim();if(!videoUrl)return setStatus('sourceStatus','Please paste a video link first.');$('importBtn').disabled=true;setStatus('sourceStatus','Creating processing job…');try{const r=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoUrl,sourceLanguage:$('sourceLanguage').value,targetLanguage:$('targetLanguage').value,voice:$('voiceSelect').value,keepMusic:$('keepMusic').checked,separateTracks:$('separateTracks').checked})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create job.');currentJob=d.job;transcriptText='';translatedText='';transcriptId=null;setStatus('sourceStatus',`Job ${currentJob.id.slice(0,8)} created.`,true);setStatus('subtitleStatus','Ready to create subtitles.',true);}catch(e){setStatus('sourceStatus',e.message);}finally{$('importBtn').disabled=false;}});
$('videoFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;selectedLocalFile=f;currentJob=null;transcriptText='';translatedText='';const u=URL.createObjectURL(f);$('previewBox').innerHTML=`<video controls playsinline style="width:100%;max-height:420px;border-radius:18px;background:#000" src="${u}"></video>`;setStatus('sourceStatus',`Selected: ${f.name}. Local preview ready.`,true);});
$('subtitleBtn').addEventListener('click',async()=>{const mediaUrl=$('videoLink').value.trim();if(!currentJob||!mediaUrl)return setStatus('subtitleStatus','Import a public video URL first.');$('subtitleBtn').disabled=true;setStatus('subtitleStatus','Starting transcription…');try{const r=await fetch('/api/transcribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mediaUrl,sourceLanguage:$('sourceLanguage').value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to start transcription.');transcriptId=d.transcript.id;const result=await pollTranscript(transcriptId);translatedText=transcriptText;if(transcriptText&&$('targetLanguage').value!=='English'){setStatus('subtitleStatus',`Transcript ready${result.language?` (${result.language})`:''}. Translating to ${$('targetLanguage').value}…`);translatedText=await translateText(transcriptText);}const p=(translatedText||transcriptText).slice(0,180);setStatus('subtitleStatus',`Subtitles ready: ${p}${p.length>=180?'…':''}`,true);setStatus('voiceStatus','Translated transcript ready for AI voice.',true);}catch(e){setStatus('subtitleStatus',e.message||'Subtitle generation failed.');}finally{$('subtitleBtn').disabled=false;}});
$('voicePreview').addEventListener('click',async()=>{const text=(translatedText||transcriptText||'Welcome to Nexora Video AI. This is a licensed AI voice preview.').slice(0,220);$('voicePreview').disabled=true;setStatus('voiceStatus','Generating voice preview…');try{const u=await generateVoiceAudio(text);await new Audio(u).play();setStatus('voiceStatus',`Playing ${$('voiceSelect').value}.`,true);}catch(e){setStatus('voiceStatus',e.message);}finally{$('voicePreview').disabled=false;}});
$('generateVoice').addEventListener('click',async()=>{const text=translatedText||transcriptText;if(!text)return setStatus('voiceStatus','Create subtitles first.');$('generateVoice').disabled=true;setStatus('voiceStatus','Generating AI voice…');try{await generateVoiceAudio(text.slice(0,4000));setStatus('voiceStatus',`Voice generated in ${$('targetLanguage').value}.`,true);}catch(e){setStatus('voiceStatus',e.message);}finally{$('generateVoice').disabled=false;}});
$('exportBtn').addEventListener('click',()=>{if(!currentJob&&!selectedLocalFile)return setStatus('exportStatus','Create/import a video job first.');if(!lastVoiceUrl)return setStatus('exportStatus','Generate voice before export.');setStatus('exportStatus','Voice is ready. Cloud renderer requires a persistent voice file URL; renderer adapter is prepared.',true);});
fetch('/api/health').then(r=>r.json()).then(d=>{if(d.ok)console.info(`${d.service} backend ${d.version} online`);}).catch(()=>{});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
